# Arquivo de configuração do Streamlit

[theme]
base="dark"
primaryColor="green"

# Configurações de layout
[server]
headless = true                        # Necessário para quando for usar em nuvem
port = 8501                            # Porta padrão do Streamlit
enableCORS = false                     # Para evitar problemas de CORS
enableXsrfProtection = false
